from .nodes import (
    NODE_CLASS_MAPPINGS as _NOTE_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _NOTE_NAMES,
)
from .temporal import (
    NODE_CLASS_MAPPINGS as _CURVE_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _CURVE_NAMES,
)

NODE_CLASS_MAPPINGS = {**_NOTE_CLASSES, **_CURVE_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**_NOTE_NAMES, **_CURVE_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
